"""SBOM 生成。

守三件事：四条来源一条都不能漏、输出必须逐字节确定（否则"重新生成后无 diff"
这道门禁立不住）、bom-ref 不许撞车。
"""
from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import generate_sbom as gs                                  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]

LOCK = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    uv pip compile requirements-deploy.txt --universal "
    "--python-version 3.10 --generate-hashes -o requirements-deploy.lock.txt\n"
    "alembic==1.18.5 \\\n"
    "    --hash=sha256:bbb \\\n"
    "    --hash=sha256:aaa\n"
    "websockets==16.1.1 ; python_full_version < '3.11' \\\n"
    "    --hash=sha256:ccc\n"
    "websockets==17.0.1 ; python_full_version >= '3.11' \\\n"
    "    --hash=sha256:ddd\n"
)
DOCKERFILE = (
    "FROM node:22-alpine@sha256:" + "1" * 64 + " AS web\n"
    "RUN npm ci\n"
    "FROM python:3.12-alpine3.24@sha256:" + "2" * 64 + " AS runtime\n"
    "RUN apk add --no-cache bash=5.3.9-r1\n"
)
NPM_LOCK = {
    "lockfileVersion": 3,
    "packages": {
        "": {"name": "web", "version": "0.0.0"},
        "node_modules/react": {"version": "19.2.0", "integrity": "sha512-r",
                               "resolved": "https://registry.npmjs.org/react/-/react-19.2.0.tgz"},
        "node_modules/@vitejs/plugin-react": {"version": "5.1.0", "dev": True,
                                              "integrity": "sha512-v"},
        "node_modules/typescript": {},                      # 没有版本的条目要跳过
    },
}


def _build(**overrides):
    kwargs = {"lock_text": LOCK, "npm_lock": NPM_LOCK, "dockerfile": DOCKERFILE,
              "application_version": "test"}
    kwargs.update(overrides)
    return gs.build_sbom(**kwargs)


def _purls(sbom) -> list[str]:
    return [component["purl"] for component in sbom["components"]]


def test_all_four_sources_land_in_one_document():
    sbom, unpinned = _build()
    assert unpinned == []
    assert set(_purls(sbom)) == {
        "pkg:pypi/alembic@1.18.5",
        "pkg:pypi/websockets@16.1.1",
        "pkg:pypi/websockets@17.0.1",
        "pkg:npm/react@19.2.0",
        "pkg:npm/%40vitejs/plugin-react@5.1.0",
        "pkg:oci/node@sha256:" + "1" * 64,
        "pkg:oci/python@sha256:" + "2" * 64,
        "pkg:apk/alpine/bash@5.3.9-r1",
    }
    assert sbom["bomFormat"] == "CycloneDX" and sbom["specVersion"] == "1.6"


def test_dev_dependencies_are_included_because_the_build_is_supply_chain():
    """构建期工具能改掉发给老人的 dist，"运行期用不到"不是把它排除的理由。"""
    sbom, _ = _build()
    by_purl = {c["purl"]: c for c in sbom["components"]}
    dev = by_purl["pkg:npm/%40vitejs/plugin-react@5.1.0"]
    assert dev["scope"] == "optional"
    assert {"name": "nmu:npm:dev", "value": "true"} in dev["properties"]
    assert by_purl["pkg:npm/react@19.2.0"]["scope"] == "required"


def test_every_locked_hash_is_carried_and_sorted():
    sbom, _ = _build()
    alembic = next(c for c in sbom["components"] if c["purl"] == "pkg:pypi/alembic@1.18.5")
    hashes = [p["value"] for p in alembic["properties"] if p["name"] == "nmu:pypi:sha256"]
    assert hashes == ["sha256:aaa", "sha256:bbb"]           # 排过序，不随锁里顺序抖


def test_a_marker_split_package_stays_two_components():
    sbom, _ = _build()
    versions = sorted(c["version"] for c in sbom["components"]
                      if c["name"] == "websockets")
    assert versions == ["16.1.1", "17.0.1"]


def test_unpinned_apk_packages_are_reported_not_swallowed():
    _, unpinned = _build(dockerfile=DOCKERFILE.replace(
        "bash=5.3.9-r1", "bash=5.3.9-r1 curl"))
    assert unpinned == ["curl"]


def test_output_is_byte_identical_across_runs_and_has_no_timestamp():
    first, _ = _build()
    second, _ = _build()
    assert gs.render(first) == gs.render(second)
    assert "timestamp" not in json.dumps(first)
    assert first["serialNumber"] == second["serialNumber"]


def test_serial_number_moves_when_a_dependency_moves():
    """内容摘要不跟着依赖走的话，serialNumber 就是个装饰。"""
    first, _ = _build()
    second, _ = _build(lock_text=LOCK.replace("alembic==1.18.5", "alembic==1.18.6"))
    assert first["serialNumber"] != second["serialNumber"]


def test_a_purl_appearing_twice_collapses_to_one_component():
    nested = json.loads(json.dumps(NPM_LOCK))
    nested["packages"]["node_modules/@vitejs/plugin-react/node_modules/react"] = {
        "version": "19.2.0", "integrity": "sha512-r", "dev": True}
    sbom, _ = _build(npm_lock=nested)
    refs = [c["bom-ref"] for c in sbom["components"]]
    assert len(refs) == len(set(refs)), "bom-ref 撞车的 CycloneDX 是非法文档"
    react = next(c for c in sbom["components"] if c["purl"] == "pkg:npm/react@19.2.0")
    assert react["scope"] == "required"                     # 严的那个赢


def test_check_mode_passes_on_a_matching_file_and_fails_on_a_stale_one(tmp_path):
    lock = tmp_path / "lock.txt"
    lock.write_text(LOCK, encoding="utf-8")
    npm = tmp_path / "package-lock.json"
    npm.write_text(json.dumps(NPM_LOCK), encoding="utf-8")
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text(DOCKERFILE, encoding="utf-8")
    out = tmp_path / "sbom.cdx.json"
    argv = ["--lock", str(lock), "--npm-lock", str(npm),
            "--dockerfile", str(dockerfile), "-o", str(out)]

    assert gs.main(argv) == 0
    assert gs.main(argv + ["--check"]) == 0

    lock.write_text(LOCK.replace("alembic==1.18.5", "alembic==1.18.6"), encoding="utf-8")
    assert gs.main(argv + ["--check"]) == 1                 # 依赖动了、SBOM 没重出


def test_check_mode_fails_when_the_file_is_missing(tmp_path):
    assert gs.main(["-o", str(tmp_path / "nope.json"), "--check"]) == 1


# ---------------- 真仓库 ----------------

def test_the_committed_sbom_matches_the_repository_as_it_stands():
    """这条就是 CI 的那道门禁。红了说明改了依赖没重出 SBOM。"""
    done = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "generate_sbom.py"), "--check"],
        capture_output=True, text=True, cwd=ROOT, timeout=300)
    assert done.returncode == 0, done.stdout + done.stderr


@pytest.mark.parametrize("purl_prefix", ["pkg:pypi/", "pkg:npm/", "pkg:oci/", "pkg:apk/"])
def test_the_committed_sbom_covers_every_source(purl_prefix):
    sbom = json.loads((ROOT / "sbom.cdx.json").read_text(encoding="utf-8"))
    assert any(c["purl"].startswith(purl_prefix) for c in sbom["components"])
