"""运行环境 ↔ 哈希锁对账。

这套用例守的是三件事：锁本身必须带哈希、marker 必须真求值（不是当真或当假
糊过去）、同名多版本必须按集合判。第三条尤其容易写错——universal 锁里
websockets 有两条（<3.11 一条、>=3.11 一条），拿单值等号比会在半数机器上误报。
"""
from __future__ import annotations

from pathlib import Path
import subprocess
import sys

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import supply_chain_check as sc                             # noqa: E402

REAL_LOCK = Path(__file__).resolve().parents[1] / "requirements-deploy.lock.txt"

LINUX_310 = {
    "implementation_name": "cpython",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "platform_system": "Linux",
    "python_full_version": "3.10.12",
    "python_version": "3.10",
    "sys_platform": "linux",
}
MACOS_314 = {**LINUX_310, "platform_machine": "arm64", "platform_system": "Darwin",
             "python_full_version": "3.14.5", "python_version": "3.14",
             "sys_platform": "darwin"}
WINDOWS_312 = {**LINUX_310, "platform_machine": "AMD64", "os_name": "nt",
               "platform_system": "Windows", "python_full_version": "3.12.8",
               "python_version": "3.12", "sys_platform": "win32"}


def _lock(*lines: str) -> str:
    return "\n".join(lines) + "\n"


def _snapshot(distributions: dict[str, str], environment=None) -> dict:
    return {"environment": dict(environment or LINUX_310),
            "distributions": dict(distributions)}


def _kinds(findings) -> list[tuple[str, str]]:
    return sorted((f.kind, f.name) for f in findings)


# ---------------- 解析 ----------------

def test_parse_lock_reads_version_marker_hashes_and_floor():
    entries, floor = sc.parse_lock(_lock(
        "# This file was autogenerated by uv via the following command:",
        "#    uv pip compile requirements-deploy.txt --universal "
        "--python-version 3.10 --generate-hashes -o requirements-deploy.lock.txt",
        "alembic==1.18.5 \\",
        "    --hash=sha256:aaa \\",
        "    --hash=sha256:bbb",
        "    # via -r requirements-deploy.txt",
        "colorama==0.4.6 ; sys_platform == 'win32' \\",
        "    --hash=sha256:ccc",
    ))
    assert floor == (3, 10)
    assert [(e.name, e.version, e.marker, len(e.hashes)) for e in entries] == [
        ("alembic", "1.18.5", None, 2),
        ("colorama", "0.4.6", "sys_platform == 'win32'", 1),
    ]


def test_parse_lock_refuses_a_line_it_does_not_understand():
    with pytest.raises(ValueError, match="看不懂的锁行"):
        sc.parse_lock(_lock("alembic>=1.18.5"))          # 锁必须是精确钉版


def test_canonical_name_folds_the_three_separators():
    assert sc.canonical("Piper_TTS") == sc.canonical("piper-tts") == "piper-tts"
    assert sc.canonical("zope.interface") == "zope-interface"


# ---------------- marker 求值 ----------------

@pytest.mark.parametrize("marker, env, expected", [
    ("sys_platform == 'win32'", LINUX_310, False),
    ("sys_platform == 'win32'", WINDOWS_312, True),
    ("python_full_version < '3.11'", LINUX_310, True),
    ("python_full_version < '3.11'", MACOS_314, False),
    ("python_full_version >= '3.11'", LINUX_310, False),
    ("implementation_name != 'pypy'", LINUX_310, True),
    ("platform_python_implementation != 'PyPy' and implementation_name != 'PyPy'",
     LINUX_310, True),
    ("platform_python_implementation != 'PyPy' and sys_platform != 'cygwin' "
     "and sys_platform != 'win32'", WINDOWS_312, False),
    ("platform_machine == 'AMD64' or platform_machine == 'aarch64' "
     "or platform_machine == 'x86_64'", LINUX_310, True),
    ("platform_machine == 'AMD64' or platform_machine == 'aarch64' "
     "or platform_machine == 'x86_64'", MACOS_314, False),
])
def test_evaluate_marker_on_the_forms_the_real_lock_uses(marker, env, expected):
    assert sc.evaluate_marker(marker, env) is expected


@pytest.mark.parametrize("marker", [
    "extra == 'standard'",                                  # 未知变量
    "python_version in '3.10 3.11'",                        # 未支持的运算符
    "(sys_platform == 'win32')",                            # 括号
    "sys_platform",                                         # 不成子句
])
def test_evaluate_marker_raises_instead_of_guessing(marker):
    with pytest.raises(sc.MarkerError):
        sc.evaluate_marker(marker, LINUX_310)


def test_version_key_puts_a_prerelease_before_its_release():
    assert sc._version_key("3.15.0b1") < sc._version_key("3.15.0")
    assert sc._version_key("3.9") < sc._version_key("3.10")   # 不是字符串比较
    with pytest.raises(sc.MarkerError):
        sc._version_key("не-версия")


# ---------------- 对账 ----------------

def test_a_package_absent_from_the_lock_is_a_hard_failure():
    entries, floor = sc.parse_lock(_lock("alembic==1.18.5 \\", "    --hash=sha256:a"))
    failures, notes, _ = sc.compare(
        entries, floor, _snapshot({"alembic": "1.18.5", "pytest": "9.1.1"}))
    assert _kinds(failures) == [("unlocked", "pytest")]
    assert notes == []


def test_a_version_the_lock_does_not_allow_is_a_hard_failure():
    entries, floor = sc.parse_lock(_lock("alembic==1.18.5 \\", "    --hash=sha256:a"))
    failures, _, _ = sc.compare(entries, floor, _snapshot({"alembic": "1.18.4"}))
    assert _kinds(failures) == [("drift", "alembic")]
    assert "1.18.4" in failures[0].detail and "1.18.5" in failures[0].detail


def test_same_name_two_versions_is_matched_by_set_membership():
    """universal 锁按 marker 分叉出两条 websockets;两边都得算对上。

    单值等号比会让 3.10 的机器看到 17.0.1、3.12 的机器看到 16.1.1，各误报一次。
    """
    entries, floor = sc.parse_lock(_lock(
        "websockets==16.1.1 ; python_full_version < '3.11' \\", "    --hash=sha256:a",
        "websockets==17.0.1 ; python_full_version >= '3.11' \\", "    --hash=sha256:b"))
    for env, installed in ((LINUX_310, "16.1.1"), (MACOS_314, "17.0.1")):
        failures, notes, _ = sc.compare(
            entries, floor, _snapshot({"websockets": installed}, env))
        assert failures == [] and notes == []
    failures, _, _ = sc.compare(
        entries, floor, _snapshot({"websockets": "16.1"}, LINUX_310))
    assert _kinds(failures) == [("drift", "websockets")]


def test_absent_is_a_note_when_the_marker_is_false_and_a_failure_when_true():
    entries, floor = sc.parse_lock(_lock(
        "colorama==0.4.6 ; sys_platform == 'win32' \\", "    --hash=sha256:a",
        "alembic==1.18.5 \\", "    --hash=sha256:b"))
    failures, notes, _ = sc.compare(entries, floor, _snapshot({"alembic": "1.18.5"}))
    assert _kinds(notes) == [("absent", "colorama")]
    assert failures == []

    failures, notes, _ = sc.compare(entries, floor, _snapshot({"colorama": "0.4.6"},
                                                              WINDOWS_312))
    assert _kinds(failures) == [("absent", "alembic")]
    assert notes == []


def test_an_unparseable_marker_fails_the_check_rather_than_being_skipped():
    entries, floor = sc.parse_lock(_lock(
        "anyio==4.14.2 ; extra == 'standard' \\", "    --hash=sha256:a"))
    failures, _, _ = sc.compare(entries, floor, _snapshot({"anyio": "4.14.2"}))
    assert _kinds(failures) == [("marker", "anyio")]


def test_python_below_the_locks_floor_is_a_hard_failure():
    text = _lock("#    uv pip compile --python-version 3.10 --generate-hashes",
                 "alembic==1.18.5 \\", "    --hash=sha256:a")
    entries, floor = sc.parse_lock(text)
    old = {**LINUX_310, "python_version": "3.9", "python_full_version": "3.9.18"}
    failures, _, _ = sc.compare(entries, floor,
                                _snapshot({"alembic": "1.18.5"}, old))
    assert ("floor", "python") in _kinds(failures)
    failures, _, _ = sc.compare(entries, floor, _snapshot({"alembic": "1.18.5"}))
    assert ("floor", "python") not in _kinds(failures)


def test_a_lock_without_hashes_fails_before_anything_else_matters():
    entries, floor = sc.parse_lock(_lock("alembic==1.18.5"))
    failures, _, _ = sc.compare(entries, floor, _snapshot({"alembic": "1.18.5"}))
    assert _kinds(failures) == [("hashed", "锁本身")]


# ---------------- 真锁 + 真解释器 ----------------

def test_the_shipped_lock_is_fully_hashed_and_every_marker_evaluates():
    """挡两种回归：有人不带 --generate-hashes 重出锁；uv 换出求值器不认识的 marker。"""
    entries, floor = sc.parse_lock(REAL_LOCK.read_text(encoding="utf-8"))
    assert floor is not None, "锁头部必须留下 --python-version，下限是判据不是装饰"
    assert entries, "锁不该是空的"
    for entry in entries:
        assert entry.hashes, f"{entry.raw_name} 没有 --hash"
        if entry.marker:
            for env in (LINUX_310, MACOS_314, WINDOWS_312):
                sc.evaluate_marker(entry.marker, env)       # 不抛即通过


def test_probe_reports_the_interpreter_that_actually_ran_it():
    snapshot = sc.probe(sys.executable)
    assert snapshot["environment"]["python_full_version"] == (
        ".".join(str(n) for n in sys.version_info[:3]))
    assert "pytest" in {sc.canonical(name) for name in snapshot["distributions"]}


def test_cli_exits_nonzero_and_prints_json_when_the_environment_drifts(tmp_path):
    lock = tmp_path / "lock.txt"
    lock.write_text(_lock("alembic==1.18.5 \\", "    --hash=sha256:a"), encoding="utf-8")
    probe = tmp_path / "probe.json"
    probe.write_text(__import__("json").dumps(
        _snapshot({"alembic": "1.18.5", "pytest": "9.1.1"})), encoding="utf-8")

    script = Path(sc.__file__)
    done = subprocess.run(
        [sys.executable, str(script), "--lock", str(lock),
         "--probe-json", str(probe), "--json"],
        capture_output=True, text=True, timeout=120)
    assert done.returncode == 1
    report = __import__("json").loads(done.stdout)
    assert report["ok"] is False
    assert [f["name"] for f in report["failures"]] == ["pytest"]


def test_cli_requires_exactly_one_source():
    script = Path(sc.__file__)
    done = subprocess.run([sys.executable, str(script)],
                          capture_output=True, text=True, timeout=120)
    assert done.returncode == 2 and "二选一" in done.stderr
