"""Static contracts for the container's runtime write boundary."""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]


def _collapsed(path: Path) -> str:
    return " ".join(path.read_text(encoding="utf-8").split())


def test_runtime_user_cannot_rewrite_application_or_training_content():
    dockerfile = (ROOT / "Dockerfile").read_text(encoding="utf-8")
    collapsed = " ".join(dockerfile.split())

    # A compromised app process must not be able to persist code, question-bank,
    # manifest, migration, script, or browser-bundle changes for later requests.
    assert not re.search(
        r"chown\s+-R\s+(?:appuser(?::appuser)?|10001(?::10001)?)\s+/app(?!/)",
        dockerfile,
    )
    assert not re.search(r"COPY\s+--chown=(?:appuser|10001)(?::\S+)?", dockerfile)
    assert (
        "chown -R root:root /app/app /app/alembic /app/content "
        "/app/scripts /app/web"
    ) in collapsed
    assert (
        "chmod -R u=rwX,go=rX /app/app /app/alembic /app/content "
        "/app/scripts /app/web"
    ) in collapsed
    assert collapsed.index("chown -R root:root") < collapsed.index("USER appuser")


def test_release_images_are_pinned_to_reviewed_multiarch_digests():
    dockerfile = (ROOT / "Dockerfile").read_text(encoding="utf-8")
    compose = (ROOT / "docker-compose.yml").read_text(encoding="utf-8")
    from_lines = [
        line.strip() for line in dockerfile.splitlines()
        if line.lstrip().startswith("FROM ")
    ]

    assert len(from_lines) == 2
    assert all(re.search(r"@sha256:[0-9a-f]{64}(?:\s|$)", line)
               for line in from_lines)
    caddy_image = next(
        line.strip() for line in compose.splitlines()
        if line.strip().startswith("image: caddy:")
    )
    assert re.fullmatch(
        r"image: caddy:2\.11\.4-alpine@sha256:[0-9a-f]{64}",
        caddy_image,
    )


def test_container_installs_complete_hash_locked_dependency_graph():
    dockerfile = _collapsed(ROOT / "Dockerfile")
    direct = (ROOT / "requirements-deploy.txt").read_text(encoding="utf-8")
    lock = (ROOT / "requirements-deploy.lock.txt").read_text(encoding="utf-8")

    assert (
        "COPY requirements-deploy.txt requirements-deploy.lock.txt ./"
        in dockerfile
    )
    assert (
        "pip install --no-cache-dir --require-hashes "
        "-r requirements-deploy.lock.txt"
    ) in dockerfile
    assert "python -m pip uninstall --yes pip" in dockerfile
    assert "apk add --no-cache bash=5.3.9-r1" in dockerfile
    assert lock.startswith("# This file was autogenerated by uv")
    assert lock.count("--hash=sha256:") > 100
    assert "--index-url" not in lock and "--extra-index-url" not in lock
    for requirement in direct.splitlines():
        requirement = requirement.strip()
        if not requirement or requirement.startswith("#"):
            continue
        package, version = requirement.split("==", 1)
        normalized = package.split("[", 1)[0].lower()
        assert re.search(
            rf"^{re.escape(normalized)}=={re.escape(version)}(?:\s|\\)",
            lock,
            re.MULTILINE,
        )


def test_only_application_data_volume_is_given_to_runtime_user():
    dockerfile = _collapsed(ROOT / "Dockerfile")
    compose = (ROOT / "docker-compose.yml").read_text(encoding="utf-8")

    assert "mkdir -p /app/data" in dockerfile
    assert "addgroup -S -g 10001 appuser" in dockerfile
    assert (
        "adduser -S -D -H -u 10001 -G appuser "
        "-s /sbin/nologin appuser"
    ) in dockerfile
    assert "chown appuser:appuser /app/data" in dockerfile
    assert "chmod 0700 /app/data" in dockerfile
    assert "chmod 0755 /app" in dockerfile
    assert "- appdata:/app/data" in compose


def test_app_container_has_read_only_root_and_no_linux_capabilities():
    compose = (ROOT / "docker-compose.yml").read_text(encoding="utf-8")
    app_block = compose.split("\n  caddy:", 1)[0]

    assert 'read_only: true' in app_block
    assert 'user: "10001:10001"' in app_block
    assert "cap_drop:\n      - ALL" in app_block
    assert "no-new-privileges:true" in app_block
    assert "pids_limit: 256" in app_block
    assert "mem_limit: 512m" in app_block
    assert "memswap_limit: 640m" in app_block
    assert "/tmp:size=16m,mode=1777,noexec,nosuid,nodev" in app_block
    # The only persistent write mount remains the private research-data volume;
    # no source/content/static bind mount may bypass the immutable rootfs.
    app_mount_targets = re.findall(
        r"^\s+-\s+[^#\n]+:(/app/[^\s#]+)", app_block, re.MULTILINE,
    )
    assert app_mount_targets == ["/app/data"]
    assert "appdata:/app/data" in app_block


def test_database_audio_processing_exports_and_backup_default_under_data_volume():
    db = _collapsed(ROOT / "app" / "db.py")
    audio = _collapsed(ROOT / "app" / "audio_store.py")
    asr = _collapsed(ROOT / "app" / "asr.py")
    tts = _collapsed(ROOT / "app" / "tts.py")
    export = _collapsed(ROOT / "app" / "export.py")
    backup = (ROOT / "scripts" / "backup.sh").read_text(encoding="utf-8")

    assert '_DATA = Path(__file__).resolve().parent.parent / "data"' in db
    assert '/ "data" / "audio"' in audio
    assert '/ "data" / "asr-scratch"' in asr
    assert 'DATA_DIR = Path(__file__).resolve().parent.parent / "data"' in tts
    assert '/ "data" / "exports"' in export
    assert '/ "data" / "controlled-audio-exports"' in export
    assert 'DATA_DIR="data"' in backup
    assert 'DEST_ROOT="${BACKUP_DIR:-$DATA_DIR/backups}"' in backup
