"""turnevent: add ai_judge_mode

Revision ID: 03bab7e0f307
Revises: 2ce0d923766e
Create Date: 2026-07-10 12:12:11.097695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 —— autogenerate 产出的 sqlmodel.AutoString 等类型需要


# revision identifiers, used by Alembic.
revision: str = '03bab7e0f307'
down_revision: Union[str, Sequence[str], None] = '2ce0d923766e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turnevent', sa.Column('ai_judge_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turnevent', 'ai_judge_mode')
    # ### end Alembic commands ###
