"""baseline: full M0 schema

Revision ID: 2ce0d923766e
Revises: 
Create Date: 2026-07-10 12:01:22.981432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 —— autogenerate 产出的 sqlmodel.AutoString 等类型需要


# revision identifiers, used by Alembic.
revision: str = '2ce0d923766e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livestate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('session_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cursor_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rapport_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dementia_severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mandarin_eligible', sa.Boolean(), nullable=True),
    sa.Column('language_eligibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_type', sa.Enum('本人同意', '代理同意加本人赞同', name='consenttype'), nullable=True),
    sa.Column('consent_time', sa.DateTime(), nullable=True),
    sa.Column('consent_person', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proxy_consent', sa.Boolean(), nullable=True),
    sa.Column('capacity_assessment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assent_obtained', sa.Boolean(), nullable=True),
    sa.Column('recording_allowed', sa.Boolean(), nullable=True),
    sa.Column('secondary_use_allowed', sa.Boolean(), nullable=True),
    sa.Column('withdrawal_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ethics_approval_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('scaleresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase_type', sa.Enum('关系建立', '基线测评', '正式训练', '前测', '后测', '随访', '探针测评', name='phasetype'), nullable=False),
    sa.Column('scale_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('assessor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scaleresult_patient_id'), 'scaleresult', ['patient_id'], unique=False)
    op.create_table('session',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_sitting_no', sa.Integer(), nullable=False),
    sa.Column('training_date', sa.Date(), nullable=True),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('phase_type', sa.Enum('关系建立', '基线测评', '正式训练', '前测', '后测', '随访', '探针测评', name='phasetype'), nullable=False),
    sa.Column('event_line', sa.Enum('关系建立环节', '基线测评窗', '正式训练', name='eventline'), nullable=False),
    sa.Column('trainer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_bank_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_session_patient_id'), 'session', ['patient_id'], unique=False)
    op.create_table('week1profile',
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_appellation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zodiac', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('daily_activities', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('familiar_places', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('familiar_people', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('common_objects', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('willing_to_continue', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('audioassetrow',
    sa.Column('raw_audio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('recorded', 'exported', 'checksum_verified', 'reliability_review_done', 'deletable', 'deleted', name='audiostatus'), nullable=False),
    sa.Column('is_reliability_sample', sa.Boolean(), nullable=False),
    sa.Column('withdrawn', sa.Boolean(), nullable=False),
    sa.Column('withdrawal_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contains_direct_identifier', sa.Boolean(), nullable=False),
    sa.Column('export_batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delete_gate_passed', sa.Boolean(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('raw_audio_id')
    )
    op.create_table('itemevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_type', sa.Enum('单要素', '双要素', '多要素', '关系建立', name='tasktype'), nullable=False),
    sa.Column('item_set_type', sa.Enum('训练集', '探针集', '画像采集', name='itemsettype'), nullable=False),
    sa.Column('difficulty_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('presentation_order', sa.Integer(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemevent_item_id'), 'itemevent', ['item_id'], unique=False)
    op.create_index(op.f('ix_itemevent_session_id'), 'itemevent', ['session_id'], unique=False)
    op.create_table('abnormalevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_event_id', sa.Integer(), nullable=True),
    sa.Column('phase_type', sa.Enum('关系建立', '基线测评', '正式训练', '前测', '后测', '随访', '探针测评', name='phasetype'), nullable=True),
    sa.Column('abnormal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intervention_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affects_scoring_validity', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_event_id'], ['itemevent.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abnormalevent_session_id'), 'abnormalevent', ['session_id'], unique=False)
    op.create_table('turnevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_event_id', sa.Integer(), nullable=False),
    sa.Column('turn_seq', sa.Integer(), nullable=False),
    sa.Column('response_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_audio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('confirmed_response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('naming_latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_level', sa.Integer(), nullable=True),
    sa.Column('cue_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_answer_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_needs_review', sa.Boolean(), nullable=True),
    sa.Column('judge_portrait_used', sa.Boolean(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_score', sa.Float(), nullable=True),
    sa.Column('score_locked', sa.Boolean(), nullable=False),
    sa.Column('element_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_event_id'], ['itemevent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnevent_item_event_id'), 'turnevent', ['item_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turnevent_item_event_id'), table_name='turnevent')
    op.drop_table('turnevent')
    op.drop_index(op.f('ix_abnormalevent_session_id'), table_name='abnormalevent')
    op.drop_table('abnormalevent')
    op.drop_index(op.f('ix_itemevent_session_id'), table_name='itemevent')
    op.drop_index(op.f('ix_itemevent_item_id'), table_name='itemevent')
    op.drop_table('itemevent')
    op.drop_table('audioassetrow')
    op.drop_table('week1profile')
    op.drop_index(op.f('ix_session_patient_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_scaleresult_patient_id'), table_name='scaleresult')
    op.drop_table('scaleresult')
    op.drop_table('patient')
    op.drop_table('livestate')
    # ### end Alembic commands ###
