"""livestate patient_rec_json

Revision ID: 794480f21ed4
Revises: 03bab7e0f307
Create Date: 2026-07-11 11:39:21.690358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 —— autogenerate 产出的 sqlmodel.AutoString 等类型需要


# revision identifiers, used by Alembic.
revision: str = '794480f21ed4'
down_revision: Union[str, Sequence[str], None] = '03bab7e0f307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestate', sa.Column('patient_rec_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livestate', 'patient_rec_json')
    # ### end Alembic commands ###
