"""questionnaire prototype records

Revision ID: b6d4f8a2c917
Revises: 6f2a9c4d8e17
Create Date: 2026-08-20

量表电子记录（原型道）：承载临床提供、待终确认的人工评价量表
（SFACS / GDS-15 / NPI-Q），逐条目 AI 初评列与人工终值列并排永久留存。
与正式结局契约（AssessmentInstance 系）是两条独立的道；定义包 status
只允许 prototype，装载器拒绝任何自称正式的包。

Downgrade fail-closed：两表存在任何一行即拒绝——已录入的量表作答是
临床证据，不因回滚被丢弃。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 —— autogenerate 产出的 sqlmodel.AutoString 等类型需要


# revision identifiers, used by Alembic.
revision: str = 'b6d4f8a2c917'
down_revision: Union[str, Sequence[str], None] = '6f2a9c4d8e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnairerecord',
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('questionnaire_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('locked_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('ai_draft_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_draft_engine', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_draft_at', sa.DateTime(), nullable=True),
    sa.Column('computed_total', sa.Float(), nullable=True),
    sa.Column('cutoff_met', sa.Boolean(), nullable=True),
    sa.Column('computed_flag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scoring_rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint("(status = 'draft' AND locked_by IS NULL AND locked_at IS NULL) OR (status = 'locked' AND locked_by IS NOT NULL AND locked_at IS NOT NULL)", name='ck_questionnaire_record_lock_complete'),
    sa.CheckConstraint("ai_draft_status IN ('none','not_applicable','generated','unavailable_no_data','unavailable_not_authorized','failed')", name='ck_questionnaire_record_ai_draft_status'),
    sa.CheckConstraint("phase_label IN ('前测','后测','随访','其他')", name='ck_questionnaire_record_phase_label'),
    sa.CheckConstraint("status IN ('draft','locked')", name='ck_questionnaire_record_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_questionnairerecord_patient_id'), 'questionnairerecord', ['patient_id'], unique=False)
    op.create_table('questionnaireitemvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_draft_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_draft_rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("value_source IS NULL OR value_source IN ('human_direct','ai_accepted','ai_overridden')", name='ck_questionnaire_item_value_source'),
    sa.ForeignKeyConstraint(['record_id'], ['questionnairerecord.record_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'item_key', 'field_key', name='uq_questionnaire_item_value_slot')
    )
    op.create_index(op.f('ix_questionnaireitemvalue_record_id'), 'questionnaireitemvalue', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema; refuses while any questionnaire evidence exists."""
    connection = op.get_bind()
    for table in ("questionnaireitemvalue", "questionnairerecord"):
        count = connection.execute(
            sa.text(f"SELECT COUNT(*) FROM {table}")).scalar_one()
        if count:
            raise RuntimeError(
                f"downgrade refused: {table} 存在 {count} 行量表证据，"
                "回滚不得丢弃已录入作答")
    op.drop_index(op.f('ix_questionnaireitemvalue_record_id'), table_name='questionnaireitemvalue')
    op.drop_table('questionnaireitemvalue')
    op.drop_index(op.f('ix_questionnairerecord_patient_id'), table_name='questionnairerecord')
    op.drop_table('questionnairerecord')
