"""independent formal-assessment evidence contract

Revision ID: f9b2d6e4a801
Revises: e8a1c4b7d902
Create Date: 2026-07-19

This is an additive, no-backfill domain.  Legacy ``ScaleResult`` rows remain
legacy-only and are never promoted into frozen-definition formal outcomes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 —— autogenerate 产出的 sqlmodel.AutoString 等类型需要


# revision identifiers, used by Alembic.
revision: str = 'f9b2d6e4a801'
down_revision: Union[str, Sequence[str], None] = 'e8a1c4b7d902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessmentevent',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_assessor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timepoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('data_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('formal_outcome_eligible', sa.Boolean(), nullable=False),
    sa.Column('definition_bundle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_bundle_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_protocol_slot_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancelled_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("((is_simulation AND data_classification = 'simulation' AND NOT formal_outcome_eligible) OR ((NOT is_simulation) AND data_classification = 'research'))", name='ck_assessment_event_simulation_boundary'),
    sa.CheckConstraint("((status = 'cancelled' AND cancellation_reason_code IN ('schedule_changed','participant_unavailable','protocol_correction','duplicate_event') AND length(trim(cancelled_by)) > 0) OR (status != 'cancelled' AND cancellation_reason_code IS NULL AND cancelled_by IS NULL))", name='ck_assessment_event_cancellation'),
    sa.CheckConstraint("((status = 'due' AND started_at IS NULL AND closed_at IS NULL AND cancelled_at IS NULL) OR (status IN ('in_progress','awaiting_closeout') AND started_at IS NOT NULL AND closed_at IS NULL AND cancelled_at IS NULL) OR (status = 'closed' AND started_at IS NOT NULL AND closed_at IS NOT NULL AND cancelled_at IS NULL) OR (status = 'cancelled' AND started_at IS NULL AND closed_at IS NULL AND cancelled_at IS NOT NULL))", name='ck_assessment_event_lifecycle_timestamps'),
    sa.CheckConstraint("((status IN ('due','in_progress','awaiting_closeout') AND active_protocol_slot_key IS NOT NULL AND length(active_protocol_slot_key) = 64) OR (status IN ('closed','cancelled') AND active_protocol_slot_key IS NULL))", name='ck_assessment_event_active_slot_lifecycle'),
    sa.CheckConstraint("data_classification IN ('research','simulation')", name='ck_assessment_event_classification'),
    sa.CheckConstraint("length(definition_bundle_digest) = 71 AND substr(definition_bundle_digest, 1, 7) = 'sha256:'", name='ck_assessment_event_bundle_digest'),
    sa.CheckConstraint("status IN ('due','in_progress','awaiting_closeout','closed','cancelled')", name='ck_assessment_event_status'),
    sa.CheckConstraint("timepoint IN ('pretest','posttest','followup')", name='ck_assessment_event_timepoint'),
    sa.CheckConstraint('length(trim(assigned_assessor_id)) > 0', name='ck_assessment_event_assessor'),
    sa.CheckConstraint('revision >= 1', name='ck_assessment_event_revision'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('active_protocol_slot_key', name='uq_assessment_event_active_protocol_slot')
    )
    op.create_index('ix_assessment_event_due_queue', 'assessmentevent', ['status', 'scheduled_date'], unique=False)
    op.create_index('ix_assessment_event_patient_timepoint', 'assessmentevent', ['patient_id', 'timepoint'], unique=False)
    op.create_index(op.f('ix_assessmentevent_active_protocol_slot_key'), 'assessmentevent', ['active_protocol_slot_key'], unique=False)
    op.create_index(op.f('ix_assessmentevent_assigned_assessor_id'), 'assessmentevent', ['assigned_assessor_id'], unique=False)
    op.create_index(op.f('ix_assessmentevent_patient_id'), 'assessmentevent', ['patient_id'], unique=False)
    op.create_table('assessmenteventcloseout',
    sa.Column('closeout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_revision', sa.Integer(), nullable=False),
    sa.Column('instance_terminal_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fatigue_observed', sa.Boolean(), nullable=False),
    sa.Column('distress_or_discomfort_observed', sa.Boolean(), nullable=False),
    sa.Column('participant_declined_to_continue', sa.Boolean(), nullable=False),
    sa.Column('staff_assistance_occurred', sa.Boolean(), nullable=False),
    sa.Column('environment_interruption_occurred', sa.Boolean(), nullable=False),
    sa.Column('device_or_network_interruption_occurred', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('idempotency_key_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('closed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("report_status != 'no_additional_observation' OR ((NOT fatigue_observed) AND (NOT distress_or_discomfort_observed) AND (NOT participant_declined_to_continue) AND (NOT staff_assistance_occurred) AND (NOT environment_interruption_occurred) AND (NOT device_or_network_interruption_occurred) AND note IS NULL)", name='ck_assessment_closeout_no_observation_empty'),
    sa.CheckConstraint("report_status != 'observation_recorded' OR (fatigue_observed OR distress_or_discomfort_observed OR participant_declined_to_continue OR staff_assistance_occurred OR environment_interruption_occurred OR device_or_network_interruption_occurred OR note IS NOT NULL)", name='ck_assessment_closeout_observation_present'),
    sa.CheckConstraint("report_status IN ('no_additional_observation','observation_recorded')", name='ck_assessment_closeout_status'),
    sa.CheckConstraint('event_revision >= 2', name='ck_assessment_closeout_event_revision'),
    sa.CheckConstraint('length(instance_terminal_digest) = 71 AND length(idempotency_key_sha256) = 64 AND length(request_hash) = 64', name='ck_assessment_closeout_digests'),
    sa.CheckConstraint('note IS NULL OR (length(note) <= 2000 AND length(trim(note)) > 0)', name='ck_assessment_closeout_note'),
    sa.ForeignKeyConstraint(['event_id'], ['assessmentevent.event_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('closeout_id'),
    sa.UniqueConstraint('event_id', name='uq_assessment_closeout_event')
    )
    op.create_index(op.f('ix_assessmenteventcloseout_event_id'), 'assessmenteventcloseout', ['event_id'], unique=False)
    op.create_index(op.f('ix_assessmenteventcloseout_patient_id'), 'assessmenteventcloseout', ['patient_id'], unique=False)
    op.create_table('assessmentinstance',
    sa.Column('instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_bundle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_bundle_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrument_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrument_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_set_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('administration_protocol_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_schema_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_schema_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('missingness_rule_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stopping_rule_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_algorithm_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_algorithm_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_algorithm_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_min', sa.Float(), nullable=False),
    sa.Column('score_max', sa.Float(), nullable=False),
    sa.Column('score_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_rounding_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('automatic_scoring_permitted', sa.Boolean(), nullable=False),
    sa.Column('item_response_storage_permitted', sa.Boolean(), nullable=False),
    sa.Column('result_storage_permitted', sa.Boolean(), nullable=False),
    sa.Column('result_export_permitted', sa.Boolean(), nullable=False),
    sa.Column('required_item_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('data_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('formal_outcome_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("((is_simulation AND data_classification = 'simulation' AND NOT formal_outcome_eligible) OR ((NOT is_simulation) AND data_classification = 'research'))", name='ck_assessment_instance_classification'),
    sa.CheckConstraint("((status = 'completed' AND completed_at IS NOT NULL) OR (status != 'completed' AND completed_at IS NULL))", name='ck_assessment_instance_completion_timestamp'),
    sa.CheckConstraint("category_key IN ('untrained_standardized_naming','functional_communication')", name='ck_assessment_instance_category'),
    sa.CheckConstraint("score_direction IN ('higher_is_better','lower_is_better')", name='ck_assessment_instance_score_direction'),
    sa.CheckConstraint("status IN ('due','in_progress','completed','approved_deferred')", name='ck_assessment_instance_status'),
    sa.CheckConstraint('NOT formal_outcome_eligible OR NOT is_simulation', name='ck_assessment_instance_simulation_boundary'),
    sa.CheckConstraint('length(definition_bundle_digest) = 71 AND length(definition_digest) = 71 AND length(item_set_digest) = 71 AND length(administration_protocol_digest) = 71 AND length(response_schema_digest) = 71 AND length(result_schema_digest) = 71 AND length(missingness_rule_digest) = 71 AND length(stopping_rule_digest) = 71 AND length(scoring_algorithm_digest) = 71', name='ck_assessment_instance_digest_lengths'),
    sa.CheckConstraint('required_item_count >= 1', name='ck_assessment_instance_required_items'),
    sa.CheckConstraint('revision >= 1', name='ck_assessment_instance_revision'),
    sa.CheckConstraint('score_min < score_max', name='ck_assessment_instance_score_range'),
    sa.ForeignKeyConstraint(['event_id'], ['assessmentevent.event_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('instance_id'),
    sa.UniqueConstraint('event_id', 'category_key', name='uq_assessment_instance_event_category')
    )
    op.create_index('ix_assessment_instance_patient_status', 'assessmentinstance', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_assessmentinstance_category_key'), 'assessmentinstance', ['category_key'], unique=False)
    op.create_index(op.f('ix_assessmentinstance_event_id'), 'assessmentinstance', ['event_id'], unique=False)
    op.create_index(op.f('ix_assessmentinstance_patient_id'), 'assessmentinstance', ['patient_id'], unique=False)
    op.create_table('assessmentcommand',
    sa.Column('command_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('command_seq', sa.Integer(), nullable=False),
    sa.Column('command_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_event_revision', sa.Integer(), nullable=False),
    sa.Column('resulting_event_revision', sa.Integer(), nullable=False),
    sa.Column('expected_target_revision', sa.Integer(), nullable=True),
    sa.Column('resulting_target_revision', sa.Integer(), nullable=True),
    sa.Column('result_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("((command_type = 'cancel' AND reason_code IN ('schedule_changed','participant_unavailable','protocol_correction','duplicate_event')) OR (command_type != 'cancel' AND reason_code IS NULL))", name='ck_assessment_command_reason'),
    sa.CheckConstraint("actor_role IN ('researcher','admin','system','local_m0')", name='ck_assessment_command_actor_role'),
    sa.CheckConstraint("command_type IN ('create','start','response','complete','defer','close','cancel')", name='ck_assessment_command_type'),
    sa.CheckConstraint("((command_type IN ('response','complete','defer') AND instance_id IS NOT NULL AND expected_target_revision IS NOT NULL AND resulting_target_revision = expected_target_revision + 1) OR (command_type IN ('create','start','close','cancel') AND instance_id IS NULL AND expected_target_revision IS NULL AND resulting_target_revision IS NULL))", name='ck_assessment_command_target_revision'),
    sa.CheckConstraint("((command_type = 'response' AND item_key IS NOT NULL AND length(trim(item_key)) > 0) OR (command_type != 'response' AND item_key IS NULL))", name='ck_assessment_command_item_binding'),
    sa.CheckConstraint("((command_type IN ('create','start','cancel') AND result_entity_type = 'assessment_event' AND result_entity_id = event_id) OR (command_type = 'response' AND result_entity_type = 'assessment_item_response') OR (command_type = 'complete' AND result_entity_type = 'assessment_scoring_evidence') OR (command_type = 'defer' AND result_entity_type = 'assessment_deferral_approval') OR (command_type = 'close' AND result_entity_type = 'assessment_event_closeout'))", name='ck_assessment_command_result_entity'),
    sa.CheckConstraint('length(trim(actor_id)) > 0', name='ck_assessment_command_actor'),
    sa.CheckConstraint('command_seq >= 1', name='ck_assessment_command_seq'),
    sa.CheckConstraint('expected_event_revision >= 0 AND resulting_event_revision = expected_event_revision + 1', name='ck_assessment_command_event_revision'),
    sa.CheckConstraint('length(idempotency_key_sha256) = 64 AND length(request_hash) = 64', name='ck_assessment_command_hashes'),
    sa.ForeignKeyConstraint(['event_id'], ['assessmentevent.event_id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['assessmentinstance.instance_id'], ),
    sa.PrimaryKeyConstraint('command_id'),
    sa.UniqueConstraint('event_id', 'command_seq', name='uq_assessment_command_event_seq'),
    sa.UniqueConstraint('idempotency_key_sha256', name='uq_assessment_command_idempotency_hash')
    )
    op.create_index('ix_assessment_command_event_created', 'assessmentcommand', ['event_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assessmentcommand_event_id'), 'assessmentcommand', ['event_id'], unique=False)
    op.create_index(op.f('ix_assessmentcommand_instance_id'), 'assessmentcommand', ['instance_id'], unique=False)
    op.create_table('assessmentdeferralapproval',
    sa.Column('deferral_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deferred_until', sa.Date(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("approved_role IN ('admin','local_m0')", name='ck_assessment_deferral_approver_role'),
    sa.CheckConstraint("reason_code IN ('participant_unavailable','clinical_or_safety','technical_failure','authorized_reschedule')", name='ck_assessment_deferral_reason'),
    sa.CheckConstraint('length(definition_digest) = 71', name='ck_assessment_deferral_definition_digest'),
    sa.CheckConstraint('length(trim(approved_by)) > 0', name='ck_assessment_deferral_approver'),
    sa.ForeignKeyConstraint(['event_id'], ['assessmentevent.event_id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['assessmentinstance.instance_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('deferral_id'),
    sa.UniqueConstraint('instance_id', name='uq_assessment_deferral_instance')
    )
    op.create_index(op.f('ix_assessmentdeferralapproval_event_id'), 'assessmentdeferralapproval', ['event_id'], unique=False)
    op.create_index(op.f('ix_assessmentdeferralapproval_instance_id'), 'assessmentdeferralapproval', ['instance_id'], unique=False)
    op.create_index(op.f('ix_assessmentdeferralapproval_patient_id'), 'assessmentdeferralapproval', ['patient_id'], unique=False)
    op.create_table('assessmentitemresponse',
    sa.Column('response_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_revision', sa.Integer(), nullable=False),
    sa.Column('expected_item_revision', sa.Integer(), nullable=False),
    sa.Column('instance_revision', sa.Integer(), nullable=False),
    sa.Column('event_revision', sa.Integer(), nullable=False),
    sa.Column('response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authorized_artifact_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('instance_revision >= 2 AND event_revision >= 2', name='ck_assessment_response_parent_revisions'),
    sa.CheckConstraint('item_revision = expected_item_revision + 1', name='ck_assessment_response_item_revision_transition'),
    sa.CheckConstraint('length(idempotency_key_sha256) = 64 AND length(request_hash) = 64', name='ck_assessment_response_request_hashes'),
    sa.CheckConstraint('length(response_digest) = 71 AND (authorized_artifact_digest IS NULL OR length(authorized_artifact_digest) = 71)', name='ck_assessment_response_digests'),
    sa.CheckConstraint('length(response_json) <= 65536', name='ck_assessment_response_json_size'),
    sa.ForeignKeyConstraint(['event_id'], ['assessmentevent.event_id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['assessmentinstance.instance_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('authorized_artifact_digest', name='uq_assessment_response_artifact_receipt_digest'),
    sa.UniqueConstraint('idempotency_key_sha256', name='uq_assessment_response_idempotency_hash'),
    sa.UniqueConstraint('instance_id', 'item_key', 'item_revision', name='uq_assessment_response_item_revision')
    )
    op.create_index('ix_assessment_response_instance_item', 'assessmentitemresponse', ['instance_id', 'item_key', 'item_revision'], unique=False)
    op.create_index(op.f('ix_assessmentitemresponse_event_id'), 'assessmentitemresponse', ['event_id'], unique=False)
    op.create_index(op.f('ix_assessmentitemresponse_instance_id'), 'assessmentitemresponse', ['instance_id'], unique=False)
    op.create_index(op.f('ix_assessmentitemresponse_item_key'), 'assessmentitemresponse', ['item_key'], unique=False)
    op.create_index(op.f('ix_assessmentitemresponse_patient_id'), 'assessmentitemresponse', ['patient_id'], unique=False)
    op.create_table('assessmentscoringevidence',
    sa.Column('evidence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_response_set_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_algorithm_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_algorithm_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_algorithm_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_schema_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_min', sa.Float(), nullable=False),
    sa.Column('score_max', sa.Float(), nullable=False),
    sa.Column('answered_item_count', sa.Integer(), nullable=False),
    sa.Column('missing_item_count', sa.Integer(), nullable=False),
    sa.Column('stopped_early', sa.Boolean(), nullable=False),
    sa.Column('stopping_reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('formal_outcome_eligible', sa.Boolean(), nullable=False),
    sa.Column('scored_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('((stopped_early AND stopping_reason_code IS NOT NULL AND length(trim(stopping_reason_code)) BETWEEN 1 AND 200) OR ((NOT stopped_early) AND stopping_reason_code IS NULL))', name='ck_assessment_scoring_stopping_facts'),
    sa.CheckConstraint('NOT formal_outcome_eligible OR NOT is_simulation', name='ck_assessment_scoring_simulation_boundary'),
    sa.CheckConstraint('answered_item_count >= 0 AND missing_item_count >= 0', name='ck_assessment_scoring_counts'),
    sa.CheckConstraint('length(definition_digest) = 71 AND length(item_response_set_digest) = 71 AND length(scoring_algorithm_digest) = 71 AND length(result_digest) = 71', name='ck_assessment_scoring_digests'),
    sa.CheckConstraint('length(result_json) <= 65536', name='ck_assessment_scoring_result_json_size'),
    sa.CheckConstraint('score >= score_min AND score <= score_max', name='ck_assessment_scoring_range'),
    sa.ForeignKeyConstraint(['event_id'], ['assessmentevent.event_id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['assessmentinstance.instance_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('evidence_id'),
    sa.UniqueConstraint('instance_id', name='uq_assessment_scoring_instance')
    )
    op.create_index(op.f('ix_assessmentscoringevidence_event_id'), 'assessmentscoringevidence', ['event_id'], unique=False)
    op.create_index(op.f('ix_assessmentscoringevidence_instance_id'), 'assessmentscoringevidence', ['instance_id'], unique=False)
    op.create_index(op.f('ix_assessmentscoringevidence_patient_id'), 'assessmentscoringevidence', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessmentscoringevidence_patient_id'), table_name='assessmentscoringevidence')
    op.drop_index(op.f('ix_assessmentscoringevidence_instance_id'), table_name='assessmentscoringevidence')
    op.drop_index(op.f('ix_assessmentscoringevidence_event_id'), table_name='assessmentscoringevidence')
    op.drop_table('assessmentscoringevidence')
    op.drop_index(op.f('ix_assessmentitemresponse_patient_id'), table_name='assessmentitemresponse')
    op.drop_index(op.f('ix_assessmentitemresponse_item_key'), table_name='assessmentitemresponse')
    op.drop_index(op.f('ix_assessmentitemresponse_instance_id'), table_name='assessmentitemresponse')
    op.drop_index(op.f('ix_assessmentitemresponse_event_id'), table_name='assessmentitemresponse')
    op.drop_index('ix_assessment_response_instance_item', table_name='assessmentitemresponse')
    op.drop_table('assessmentitemresponse')
    op.drop_index(op.f('ix_assessmentdeferralapproval_patient_id'), table_name='assessmentdeferralapproval')
    op.drop_index(op.f('ix_assessmentdeferralapproval_instance_id'), table_name='assessmentdeferralapproval')
    op.drop_index(op.f('ix_assessmentdeferralapproval_event_id'), table_name='assessmentdeferralapproval')
    op.drop_table('assessmentdeferralapproval')
    op.drop_index(op.f('ix_assessmentcommand_instance_id'), table_name='assessmentcommand')
    op.drop_index(op.f('ix_assessmentcommand_event_id'), table_name='assessmentcommand')
    op.drop_index('ix_assessment_command_event_created', table_name='assessmentcommand')
    op.drop_table('assessmentcommand')
    op.drop_index(op.f('ix_assessmentinstance_patient_id'), table_name='assessmentinstance')
    op.drop_index(op.f('ix_assessmentinstance_event_id'), table_name='assessmentinstance')
    op.drop_index(op.f('ix_assessmentinstance_category_key'), table_name='assessmentinstance')
    op.drop_index('ix_assessment_instance_patient_status', table_name='assessmentinstance')
    op.drop_table('assessmentinstance')
    op.drop_index(op.f('ix_assessmenteventcloseout_patient_id'), table_name='assessmenteventcloseout')
    op.drop_index(op.f('ix_assessmenteventcloseout_event_id'), table_name='assessmenteventcloseout')
    op.drop_table('assessmenteventcloseout')
    op.drop_index(op.f('ix_assessmentevent_patient_id'), table_name='assessmentevent')
    op.drop_index(op.f('ix_assessmentevent_assigned_assessor_id'), table_name='assessmentevent')
    op.drop_index(op.f('ix_assessmentevent_active_protocol_slot_key'), table_name='assessmentevent')
    op.drop_index('ix_assessment_event_patient_timepoint', table_name='assessmentevent')
    op.drop_index('ix_assessment_event_due_queue', table_name='assessmentevent')
    op.drop_table('assessmentevent')
    # ### end Alembic commands ###
